name = "SeisSplit"
uuid = "f05a75a8-0205-5d86-a1c6-ce5881d793bb"
version = "0.6.0"
authors = ["Andy Nowacki <a.nowacki@leeds.ac.uk>"]

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Geodesics = "6aaf26a4-c633-11e8-35ae-8904cb805353"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Seis = "dd80f4d8-c2f6-58bd-9bd3-4635f134261d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[sources.Geodesics]
url = "https://github.com/anowacki/Geodesics.jl"

[sources.Seis]
url = "https://github.com/anowacki/Seis.jl"

[extensions]
SeisSplitMakieExt = "Makie"

[compat]
DelimitedFiles = "1"
Makie = "0.22, 0.23, 0.24"
StaticArrays = "0.12, 1"
julia = "1.11"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Dates", "Test", "Random"]
